name: .NET 9 Build Steps

on:
  workflow_call:
    inputs:
      version:
        description: 'The version of .NET to build'
        required: true
        type: string
      architecture:
        description: 'The architecture to build for'
        required: true
        type: string

env:
  RUNTIME_OS: linux
  RUNTIME_CONFIGURATION: Release
  RUNTIME_ARCH: "${{ inputs.architecture }}"
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_VERSION_TO_BUILD: "${{ inputs.version }}"
  PLATFORMS_TO_BUILD: "linux/${{ inputs.architecture }}"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/gold-bull/dotnet-build-deps:ubuntu-20.04-latest"
    defaults:
      run:
        shell: bash
    outputs:
      dotnet_version_short: ${{ steps.dotnet_runtime.outputs.dotnet_version_short }}
    env:
      WORKSPACE_CODE_DIR: "${{ github.workspace }}/dotnet"
      WORKSPACE_MNT_CODE_DIR: "/mnt/dotnet"
    steps:
      - name: Create required directories
        run: |-
          mkdir -p "${WORKSPACE_MNT_CODE_DIR}"
          ln -s "${WORKSPACE_MNT_CODE_DIR}" "${WORKSPACE_CODE_DIR}"
          
      - name: Checkout .NET repo
        uses: actions/checkout@v4
        with:
          repository: dotnet/dotnet
          submodules: true
          ref: "v${{ env.DOTNET_VERSION_TO_BUILD }}"
          path: "${{ env.WORKSPACE_CODE_DIR }}"

      - name: Build .NET
        id: dotnet_runtime
        run: |-
          echo "dotnet_version_short=${DOTNET_VERSION_TO_BUILD:0:3}" >> "$GITHUB_OUTPUT"
          
          export ROOTFS_DIR="/crossfs/${RUNTIME_ARCH}"

          chmod +x ./prep-source-build.sh

          ./prep-source-build.sh

          chmod +x ./build.sh

          ./build.sh -- /p:TargetOS=linux /p:TargetArchitecture=s390x
        working-directory: "${{ env.WORKSPACE_CODE_DIR }}"

      #- name: Upload NuGet Packages
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: "nuget-packages-${{ env.RUNTIME_ARCH }}"
      #    path: "${{ env.WORKSPACE_PACKAGES_DIR }}"
      #    retention-days: ${{ startsWith(github.ref, 'refs/heads/releases/') && 30 || 7 }}

      - name: Upload Archives
        uses: actions/upload-artifact@v4
        with:
          name: "archives-${{ env.RUNTIME_ARCH }}"
          #path: "${{ env.WORKSPACE_DOWNLOADS_DIR }}"
          path: "${{ env.WORKSPACE_CODE_DIR }}/artifacts"
          retention-days: ${{ startsWith(github.ref, 'refs/heads/releases/') && 30 || 7 }}

      - name: Cleanup
        if: ${{ always() }}
        run: |-
          rm -rf "${WORKSPACE_CODE_DIR}"
          rm -rf "${WORKSPACE_MNT_CODE_DIR}"

  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout .NET repo
        uses: actions/checkout@v4

      - id: qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - id: setup_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: nuget-packages-${{ env.RUNTIME_ARCH }}
          merge-multiple: true
          path: ${{ github.workspace }}/nuget-packages
      
      - name: Build and Run tests
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.PLATFORMS_TO_BUILD }}
          provenance: false
          context: "${{ github.workspace }}"
          file: "${{ github.workspace }}/tests/${{ needs.build.outputs.dotnet_version_short }}/simple/Dockerfile"
          push: false
          builder: ${{ steps.setup_buildx.outputs.name }}
          build-args: |
            RUNTIME_FRAMEWORK_VERSION=${{ inputs.version }}
            DOTNET_SDK_VERSION=${{ needs.build.outputs.dotnet_version_short }}