name: .NET 8

on:
  push:
      branches:
        - main
        - feature/*
      tags:
        - "[0-9]+-[0-9]+-[0-9]+"
      paths:
        - ".github/workflows/dotnet-8.yml"
        - ".github/workflows/dotnet-lnx.yml"
        - "tests/8.0/**"
  pull_request:
      branches:
        - main

jobs:
  build-test-publish:
    strategy:
      matrix:
        architecture:
          - s390x
    name: "Build, Test, Publish (${{ matrix.architecture }})"
    uses: ./.github/workflows/dotnet-lnx.yml
    with:
      version: "8.0.11"
      architecture: ${{ matrix.architecture }}
      docker_image: 'ghcr.io/gold-bull/dotnet-build-deps:ubuntu-20.04-latest'
