name: .NET 7

on:
  push:
      branches:
        - main
        - feature/*
        - releases/v7
      paths:
        - ".github/workflows/dotnet-7*.yml"
        - "tests/7.0/**"
  pull_request:
      branches:
        - main
        - releases/v7

env:
  DOTNET_VERSION: "7.0.18"

jobs:
  pre-execution:
    name: "Pre-execution"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      dotnet_version: ${{ steps.information.outputs.dotnet_version }}
    steps:
      - name: Gather Information
        id: information
        run: |-
          echo "dotnet_version=${{ env.DOTNET_VERSION }}" >> "$GITHUB_OUTPUT"

  build-test:
    needs:
      - pre-execution
    strategy:
      matrix:
        architecture:
          - s390x
    name: "Build & Test (${{ matrix.architecture }})"
    uses: ./.github/workflows/dotnet-7-lnx-build.yml
    with:
      architecture: ${{ matrix.architecture }}
      version: ${{ needs.pre-execution.outputs.dotnet_version }}

  publish:
    name: "Publish"
    if: ${{ github.ref == 'refs/heads/releases/v7' }}

    environment: packages-publish
    needs:
      - pre-execution
      - build-test
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: nuget-packages-*
          merge-multiple: true
          path: "${{ github.workspace }}/nuget"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: archives-*
          merge-multiple: true
          path: "${{ github.workspace }}/archives"

      - name: Upload Packages
        run: |
          rm -f *.symbols.nupkg
          
          dotnet nuget push "*.nupkg" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        working-directory: "${{ github.workspace }}/nuget"

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Install and run azcopy
        run: |-
          wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
          chmod +x ./azcopy
          export AZCOPY_AUTO_LOGIN_TYPE=AZCLI
          ./azcopy copy './*' 'https://sasgrsv2cind59037.blob.core.windows.net/dotnet/${{ needs.pre-execution.outputs.dotnet_version }}/'
        working-directory: "${{ github.workspace }}/archives"
  