name: .NET 6

on:
  push:
      branches:
        - main
        - feature/*
      tags:
        - "[0-9]+-[0-9]+-[0-9]+"
      paths:
        - ".github/workflows/dotnet-6.yml"
        - ".github/workflows/dotnet-lnx.yml"
        - "tests/6.0/**"
  pull_request:
      branches:
        - main

jobs:
  build-test-publish:
    strategy:
      matrix:
        architecture:
          - s390x
    name: "Build, Test, Publish (${{ matrix.architecture }})"
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/dotnet-lnx.yml
    with:
      version: "6.0.36"
      architecture: ${{ matrix.architecture }}
      docker_image: 'ghcr.io/gold-bull/dotnet-build-deps:ubuntu-18.04-latest'
