name: .NET 8

on:
  push:
      branches:
        - main
        - feature/*
        - releases/v8
      paths:
        - ".github/workflows/dotnet-8*.yml"
        - "tests/8.0/**"
  pull_request:
      branches:
        - main
        - releases/v8

jobs:
  build-test:
    strategy:
      matrix:
        architecture:
          - s390x
    name: "Build & Test (${{ matrix.architecture }})"
    uses: ./.github/workflows/dotnet-8-lnx-build.yml
    with:
      architecture: ${{ matrix.architecture }}
      version: "8.0.4"

  publish:
    name: "Publish"
    if: ${{ github.ref == 'refs/heads/releases/v8' }}

    environment: packages-publish
    needs:
      - build-test
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: nuget-packages-*
          merge-multiple: true
          path: "${{ github.workspace }}/nuget"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: archives-*
          merge-multiple: true
          path: "${{ github.workspace }}/archives"

      - name: Upload Packages
        run: |
          rm -f *.symbols.nupkg
          
          dotnet nuget push "*.nupkg" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
