name: .NET 8

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of .NET to build'
        required: true
        default: '8.0.0'
        type: string
  push:
      branches:
      - main
      - releases/*
  pull_request:
      branches:
      - main
      - releases/*

jobs:
  build-test:
    strategy:
      matrix:
        architecture:
          - s390x
    name: "Build & Test (${{ matrix.architecture }})"
    uses: ./.github/workflows/dotnet-8-lnx-build.yml
    with:
      architecture: ${{ matrix.architecture }}
      version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || '8.0.0' }}

  publish:
    if: ${{ startsWith(github.ref, 'refs/heads/releases/') }}
    name: "Publish"
    runs-on: ubuntu-latest
    needs:
      - build-test
    environment: packages-publish
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages-*
        merge-multiple: true

    - name: Upload Packages
      run: |
        dotnet nuget push "**/*linux-*.nupkg" \
        --skip-duplicate \
        --api-key ${{ secrets.GITHUB_TOKEN }} \
        --source https://nuget.pkg.github.com/${{ github.repository_owner }}
